services:
  db_daily_diet:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin123"
      MYSQL_DATABASE: "daily_diet"
      MYSQL_ROOT_PASSWORD: "admin123"
    ports:
      - "3307:3306"
    expose:
      # Opens port 3306 on the container
      - "3307"
    volumes:
      - C:\Users\ngcsm\Documents\workspace\mysql_daily_diet:/var/lib/mysql
